package com.github.johantiden.adventofcode._2019;

import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class D06Test {


    public static final List<A2019_06.Edge> INPUT = A2019_06.parseInput(
            "XV5)LZ5\n" +
                    "6JC)7ZG\n" +
                    "NCW)VDZ\n" +
                    "CPM)N4Z\n" +
                    "3PZ)4D6\n" +
                    "3TT)QPK\n" +
                    "G1T)FD5\n" +
                    "S43)3G7\n" +
                    "26J)ZMX\n" +
                    "GTS)G9S\n" +
                    "1GM)9ZN\n" +
                    "WCW)XTJ\n" +
                    "9B7)NTZ\n" +
                    "QDH)P9B\n" +
                    "FN2)6NB\n" +
                    "8XB)H8X\n" +
                    "638)2KM\n" +
                    "R42)M9X\n" +
                    "GX7)TGJ\n" +
                    "HB4)6SC\n" +
                    "9RP)62K\n" +
                    "W69)787\n" +
                    "T5M)H81\n" +
                    "M1C)KF5\n" +
                    "Z8D)F1Y\n" +
                    "F53)N8J\n" +
                    "BKJ)KYJ\n" +
                    "N9B)SHB\n" +
                    "QNJ)BST\n" +
                    "CD1)RVG\n" +
                    "TBD)Q68\n" +
                    "XL4)VSV\n" +
                    "Y84)L1C\n" +
                    "Q26)HGL\n" +
                    "JWN)42N\n" +
                    "MXF)XT6\n" +
                    "T5L)JCX\n" +
                    "2ZH)PQJ\n" +
                    "QJR)GWG\n" +
                    "KDY)5Y3\n" +
                    "WCS)BRL\n" +
                    "3K7)JX3\n" +
                    "CHC)MCZ\n" +
                    "WFT)GBX\n" +
                    "7NN)QVT\n" +
                    "JJY)RRG\n" +
                    "C9W)CS6\n" +
                    "CR2)J1Y\n" +
                    "GQR)X9Q\n" +
                    "WSX)3KX\n" +
                    "DCV)GQR\n" +
                    "1Z8)MC2\n" +
                    "XJP)WQC\n" +
                    "N1C)MY4\n" +
                    "J75)4CW\n" +
                    "Y35)RR1\n" +
                    "K3D)XWG\n" +
                    "VWV)LXN\n" +
                    "P18)RSW\n" +
                    "RX1)5P9\n" +
                    "DMP)XNR\n" +
                    "FNG)H83\n" +
                    "DVW)B2Q\n" +
                    "JJ4)BL4\n" +
                    "428)TLP\n" +
                    "N74)6TQ\n" +
                    "RSX)45D\n" +
                    "NM2)1JD\n" +
                    "RSX)2LL\n" +
                    "M9X)PWW\n" +
                    "W2J)DQ9\n" +
                    "DCW)WKP\n" +
                    "Q3B)FMY\n" +
                    "RPD)Y7X\n" +
                    "NZ6)4PV\n" +
                    "NM4)SGJ\n" +
                    "BBD)WWV\n" +
                    "XN6)9QQ\n" +
                    "WPZ)WJ9\n" +
                    "ST4)T72\n" +
                    "NDQ)XJ9\n" +
                    "P5G)G3N\n" +
                    "5VY)CNC\n" +
                    "GQG)SSB\n" +
                    "M7R)8QN\n" +
                    "NR8)DQJ\n" +
                    "KSW)Z8S\n" +
                    "42B)JBM\n" +
                    "BTV)985\n" +
                    "N7N)SGC\n" +
                    "GW9)6Q8\n" +
                    "73H)FSQ\n" +
                    "8GR)176\n" +
                    "RWL)XCH\n" +
                    "M3Z)RZ1\n" +
                    "1ZV)6BV\n" +
                    "6MW)TCW\n" +
                    "2HF)6JJ\n" +
                    "47B)8R6\n" +
                    "1TX)DSQ\n" +
                    "55J)GL3\n" +
                    "99Y)D27\n" +
                    "CD6)PCP\n" +
                    "VW8)JNV\n" +
                    "FNK)Q3B\n" +
                    "HWB)948\n" +
                    "3CT)XP3\n" +
                    "684)RK3\n" +
                    "TDG)4GH\n" +
                    "DZZ)NCW\n" +
                    "GR2)BJX\n" +
                    "N2M)9GR\n" +
                    "331)FGR\n" +
                    "HDQ)K74\n" +
                    "QC2)12V\n" +
                    "5TP)344\n" +
                    "QPN)4WD\n" +
                    "QJG)TWS\n" +
                    "15P)9NX\n" +
                    "4CV)WLD\n" +
                    "XGN)C88\n" +
                    "1Y6)7LB\n" +
                    "Z32)TNV\n" +
                    "G2V)QNQ\n" +
                    "673)YPW\n" +
                    "22J)628\n" +
                    "G46)7PK\n" +
                    "JN8)KZK\n" +
                    "4CW)PJS\n" +
                    "DMY)QXC\n" +
                    "7LB)L7S\n" +
                    "LQ9)X8N\n" +
                    "C3T)VWL\n" +
                    "BZ8)M2F\n" +
                    "XQ3)QKV\n" +
                    "89K)4YJ\n" +
                    "9BB)KV4\n" +
                    "X8N)1PJ\n" +
                    "PZT)98P\n" +
                    "C88)YSP\n" +
                    "LDV)T39\n" +
                    "1ZQ)SND\n" +
                    "TJJ)YKM\n" +
                    "7N4)8V8\n" +
                    "BBD)S66\n" +
                    "5MF)2X2\n" +
                    "GWW)LTH\n" +
                    "KQK)KPG\n" +
                    "FNV)HWD\n" +
                    "SMJ)HWZ\n" +
                    "M41)2W1\n" +
                    "W1G)C5D\n" +
                    "X79)P3C\n" +
                    "4KT)N5Q\n" +
                    "7BS)BWR\n" +
                    "CLX)DCW\n" +
                    "C1T)Q7C\n" +
                    "4K5)Y84\n" +
                    "63K)H8L\n" +
                    "PRZ)8JW\n" +
                    "LNM)8HG\n" +
                    "N4Z)GKB\n" +
                    "7DX)C1F\n" +
                    "BJX)LX3\n" +
                    "NWL)LK5\n" +
                    "LGW)ZXN\n" +
                    "XV7)W6H\n" +
                    "XBH)44C\n" +
                    "376)1LQ\n" +
                    "HQL)9BB\n" +
                    "PX2)3KS\n" +
                    "VHC)XP9\n" +
                    "4YZ)3XD\n" +
                    "SVN)2T8\n" +
                    "G8Z)ZP3\n" +
                    "YXP)H6D\n" +
                    "4C6)MLH\n" +
                    "BST)QV3\n" +
                    "RXP)CBM\n" +
                    "M9X)WCW\n" +
                    "5PJ)W3R\n" +
                    "98P)PXC\n" +
                    "MB3)TDG\n" +
                    "J4L)GJM\n" +
                    "6BV)59Y\n" +
                    "CNC)7P1\n" +
                    "Q7V)1H5\n" +
                    "3WF)65H\n" +
                    "MK1)SM4\n" +
                    "6JJ)YSV\n" +
                    "JFL)HC5\n" +
                    "6G7)1LD\n" +
                    "4GY)G9V\n" +
                    "B1Q)WCV\n" +
                    "3QY)K7W\n" +
                    "TSC)KDY\n" +
                    "SQS)1WB\n" +
                    "LV2)2SC\n" +
                    "FNV)4QX\n" +
                    "M2W)47Y\n" +
                    "Z8S)PQ9\n" +
                    "VSY)S88\n" +
                    "6TD)CP7\n" +
                    "DCD)4CT\n" +
                    "3NQ)R39\n" +
                    "6D5)YZC\n" +
                    "QFC)DDG\n" +
                    "XTJ)9SX\n" +
                    "SYH)Y8J\n" +
                    "KZ9)V3D\n" +
                    "32H)DD7\n" +
                    "W9V)YP3\n" +
                    "HQ1)RYK\n" +
                    "XHR)1TD\n" +
                    "7VD)4S5\n" +
                    "H81)PQR\n" +
                    "838)D9H\n" +
                    "JGT)R7V\n" +
                    "2MX)FTS\n" +
                    "1TD)CKB\n" +
                    "V2Z)F53\n" +
                    "7XL)563\n" +
                    "SM4)J3M\n" +
                    "DMP)Z9S\n" +
                    "J3G)6JC\n" +
                    "MWB)VPM\n" +
                    "NTS)V21\n" +
                    "2LG)97S\n" +
                    "9W9)CS9\n" +
                    "HLB)M2L\n" +
                    "WJ3)DTH\n" +
                    "G3S)5BD\n" +
                    "2YJ)PPH\n" +
                    "ZXK)HXX\n" +
                    "VFR)G3L\n" +
                    "1JK)L36\n" +
                    "TVV)4GY\n" +
                    "4HY)F1F\n" +
                    "JBM)XZ1\n" +
                    "BL4)X1D\n" +
                    "NF8)9KV\n" +
                    "SXX)PYS\n" +
                    "HPD)HBH\n" +
                    "RMF)HHZ\n" +
                    "4HK)5G8\n" +
                    "XZX)1ZV\n" +
                    "MCB)3YW\n" +
                    "LP4)JMQ\n" +
                    "WDL)JWB\n" +
                    "757)B3C\n" +
                    "MQX)8TY\n" +
                    "HMN)HV1\n" +
                    "J18)SKS\n" +
                    "LXJ)B41\n" +
                    "ZGV)JVM\n" +
                    "DC1)3K5\n" +
                    "QMC)SVQ\n" +
                    "VB9)2Z4\n" +
                    "WHT)BKM\n" +
                    "CDK)MS5\n" +
                    "SLQ)ZRZ\n" +
                    "7FL)GR2\n" +
                    "9T2)K81\n" +
                    "2T8)RX1\n" +
                    "DGR)PMG\n" +
                    "DGP)R3M\n" +
                    "NC8)WTV\n" +
                    "LK5)4XF\n" +
                    "132)QBZ\n" +
                    "D79)19N\n" +
                    "B4D)1FM\n" +
                    "53B)HLN\n" +
                    "HS1)RCM\n" +
                    "LQQ)CV3\n" +
                    "HJW)RB8\n" +
                    "LC7)BFM\n" +
                    "28Q)QLG\n" +
                    "CS9)G22\n" +
                    "Q98)GX7\n" +
                    "P9B)N1C\n" +
                    "JNR)VHW\n" +
                    "NVK)W4N\n" +
                    "V5R)HB4\n" +
                    "D89)5P6\n" +
                    "YQ3)LB9\n" +
                    "RSW)Q6W\n" +
                    "QM5)9XS\n" +
                    "TQM)3TT\n" +
                    "BV8)WCS\n" +
                    "9HZ)HMP\n" +
                    "4LX)XN6\n" +
                    "FGR)7Q1\n" +
                    "V9F)G1Z\n" +
                    "GBX)718\n" +
                    "2HR)SLL\n" +
                    "PZB)LGP\n" +
                    "PBC)32W\n" +
                    "5JZ)N3Y\n" +
                    "TZ9)2S1\n" +
                    "CNF)4YS\n" +
                    "T21)PKL\n" +
                    "4H2)XGN\n" +
                    "6SB)2HW\n" +
                    "R1V)LQB\n" +
                    "DCT)NKZ\n" +
                    "XTB)98Z\n" +
                    "CRZ)4LX\n" +
                    "8W7)JQQ\n" +
                    "C8M)92K\n" +
                    "3YW)YBY\n" +
                    "C76)42B\n" +
                    "R3M)FXF\n" +
                    "2VF)C12\n" +
                    "P1T)B4H\n" +
                    "ZP3)NM6\n" +
                    "KJB)JTN\n" +
                    "DTB)WMD\n" +
                    "RS8)2BX\n" +
                    "GCB)5HK\n" +
                    "4WD)F2T\n" +
                    "BZB)8NK\n" +
                    "NBK)SGD\n" +
                    "QV3)KXN\n" +
                    "WVG)4HY\n" +
                    "KRN)3VW\n" +
                    "M4Q)J75\n" +
                    "STH)T8Q\n" +
                    "GNV)5VY\n" +
                    "366)ZMV\n" +
                    "41V)PBC\n" +
                    "MHQ)3N4\n" +
                    "KVB)312\n" +
                    "K7Z)YYJ\n" +
                    "HBF)11M\n" +
                    "F2Q)17H\n" +
                    "2YZ)QV6\n" +
                    "THG)5WF\n" +
                    "S8B)V5H\n" +
                    "LY5)MQM\n" +
                    "TVK)FD6\n" +
                    "72F)QMQ\n" +
                    "LCT)HBZ\n" +
                    "LGZ)DLC\n" +
                    "RQ6)CPW\n" +
                    "V9J)Y5Y\n" +
                    "4LK)WN1\n" +
                    "F2Y)F8D\n" +
                    "WQR)RMZ\n" +
                    "Z42)JZ3\n" +
                    "QNQ)29B\n" +
                    "F1W)CFT\n" +
                    "T3J)13Q\n" +
                    "6NB)HVY\n" +
                    "G64)88J\n" +
                    "DD7)W3G\n" +
                    "CXY)CNF\n" +
                    "FD5)9C2\n" +
                    "8QH)FCS\n" +
                    "4K5)KZ9\n" +
                    "C12)NTS\n" +
                    "PJJ)298\n" +
                    "9G7)5BF\n" +
                    "HYT)GHC\n" +
                    "CVT)QKK\n" +
                    "PX2)LC7\n" +
                    "VN8)8DZ\n" +
                    "LT5)TYL\n" +
                    "12Z)RMY\n" +
                    "GRY)DRD\n" +
                    "G6R)RDJ\n" +
                    "864)ZT9\n" +
                    "DKD)N74\n" +
                    "L74)SWF\n" +
                    "2B6)4LK\n" +
                    "8V8)CLB\n" +
                    "45K)LL9\n" +
                    "YBY)JF4\n" +
                    "Q9Q)55M\n" +
                    "78F)6RM\n" +
                    "HYN)7TH\n" +
                    "7QN)HP9\n" +
                    "TB2)ZZM\n" +
                    "39D)T5W\n" +
                    "C5P)LGW\n" +
                    "DLD)RSX\n" +
                    "9RZ)HPC\n" +
                    "7TL)9T1\n" +
                    "Y3S)CRZ\n" +
                    "DTH)35N\n" +
                    "FD7)K3D\n" +
                    "YNK)FNB\n" +
                    "G1P)758\n" +
                    "68M)BQ8\n" +
                    "YMP)VW8\n" +
                    "PJZ)PJQ\n" +
                    "JJY)Y6B\n" +
                    "MD4)XNT\n" +
                    "4CS)SS5\n" +
                    "2X2)B52\n" +
                    "2TR)XL4\n" +
                    "H8X)C4N\n" +
                    "SV5)TL5\n" +
                    "CGN)QM5\n" +
                    "MXZ)GSX\n" +
                    "Z8K)JT2\n" +
                    "738)MR5\n" +
                    "2ZS)4F6\n" +
                    "QSD)NRM\n" +
                    "Q48)N1T\n" +
                    "4SH)99Y\n" +
                    "3VW)M3Z\n" +
                    "62K)HYN\n" +
                    "XTQ)9VX\n" +
                    "1FS)KF2\n" +
                    "9VL)K71\n" +
                    "XVB)7FL\n" +
                    "QHN)DSL\n" +
                    "Y6B)KRC\n" +
                    "SNJ)X8C\n" +
                    "ZDL)DPL\n" +
                    "2TR)3FH\n" +
                    "CP7)TG1\n" +
                    "3K7)L7K\n" +
                    "KQK)MK1\n" +
                    "53H)MY9\n" +
                    "7FW)S5B\n" +
                    "QL9)LF8\n" +
                    "4FG)MJY\n" +
                    "FMY)6VK\n" +
                    "G3Z)HDQ\n" +
                    "T39)BD9\n" +
                    "R6B)YFS\n" +
                    "HCX)72F\n" +
                    "QKP)RF9\n" +
                    "N1C)462\n" +
                    "9RM)B1Q\n" +
                    "TLP)7QN\n" +
                    "QSW)Q72\n" +
                    "NH3)253\n" +
                    "4TG)DCT\n" +
                    "Z4K)GV9\n" +
                    "4YS)689\n" +
                    "KSQ)P2S\n" +
                    "SV7)Z81\n" +
                    "D2J)73K\n" +
                    "RSY)FG7\n" +
                    "5PR)66Q\n" +
                    "QY8)HYT\n" +
                    "Z52)VBB\n" +
                    "3P3)7CQ\n" +
                    "GWD)3PZ\n" +
                    "GH6)RRF\n" +
                    "YQ2)YSL\n" +
                    "TQM)F6N\n" +
                    "TWT)R8N\n" +
                    "YYJ)X86\n" +
                    "LDV)362\n" +
                    "TV5)S99\n" +
                    "JTN)VHC\n" +
                    "42N)BX1\n" +
                    "LMV)XQ3\n" +
                    "Z27)Y1V\n" +
                    "DWK)RTT\n" +
                    "64J)3CT\n" +
                    "VWV)RF3\n" +
                    "NLV)1L3\n" +
                    "M4Y)JB3\n" +
                    "JGL)LR3\n" +
                    "F4T)LK7\n" +
                    "CD6)CR2\n" +
                    "167)7LW\n" +
                    "ZMV)4D3\n" +
                    "ZCY)X62\n" +
                    "G3N)VSY\n" +
                    "3SC)W6C\n" +
                    "N3Y)4KT\n" +
                    "V3D)HRV\n" +
                    "QGH)KLP\n" +
                    "XV7)JZ8\n" +
                    "YR4)CBG\n" +
                    "L6B)N1V\n" +
                    "628)STY\n" +
                    "YQX)FLG\n" +
                    "4RR)NKX\n" +
                    "L7K)SVN\n" +
                    "VBQ)SLK\n" +
                    "H3Z)BGN\n" +
                    "5P6)NY3\n" +
                    "G7X)2NG\n" +
                    "M1C)7JS\n" +
                    "658)2HR\n" +
                    "QVN)4HK\n" +
                    "6D4)NGS\n" +
                    "XNV)GH6\n" +
                    "DKJ)1CT\n" +
                    "PCP)JSF\n" +
                    "DRN)YOU\n" +
                    "88J)QVN\n" +
                    "Q4W)658\n" +
                    "LGP)FQG\n" +
                    "SWF)DYZ\n" +
                    "DRD)PSB\n" +
                    "G8Z)HTG\n" +
                    "LVD)HWB\n" +
                    "D3D)63H\n" +
                    "S94)FKM\n" +
                    "26M)RQ6\n" +
                    "Y7X)89R\n" +
                    "CPY)BZB\n" +
                    "4WQ)1ZQ\n" +
                    "XNR)XGT\n" +
                    "221)8W7\n" +
                    "T53)KP7\n" +
                    "3K3)RLH\n" +
                    "FR7)8ZB\n" +
                    "QG8)KRN\n" +
                    "G1Z)2ZS\n" +
                    "GD9)455\n" +
                    "9SX)3NC\n" +
                    "WTV)9T2\n" +
                    "D61)F1L\n" +
                    "VSJ)2SB\n" +
                    "M8D)7VD\n" +
                    "CV3)TVK\n" +
                    "TVX)VJV\n" +
                    "7P1)28Q\n" +
                    "69P)DLZ\n" +
                    "VYR)83M\n" +
                    "VQS)3Y8\n" +
                    "W34)LV2\n" +
                    "Z9S)6KV\n" +
                    "PFV)GHF\n" +
                    "YKB)CXY\n" +
                    "8NK)GL1\n" +
                    "NWF)KJB\n" +
                    "SXP)JNL\n" +
                    "JCY)DFT\n" +
                    "SKS)W7D\n" +
                    "P19)BJC\n" +
                    "MW3)WPW\n" +
                    "SPV)HVT\n" +
                    "S5T)KVN\n" +
                    "3HW)C92\n" +
                    "6HZ)W74\n" +
                    "1JD)K41\n" +
                    "CFT)WSS\n" +
                    "61T)27F\n" +
                    "4GH)Z8K\n" +
                    "D27)7H9\n" +
                    "78F)TV5\n" +
                    "HFX)NWP\n" +
                    "RHS)DQL\n" +
                    "819)4V3\n" +
                    "RGW)738\n" +
                    "Q4Y)T21\n" +
                    "RRF)248\n" +
                    "MK7)D9X\n" +
                    "55F)QFS\n" +
                    "8M8)NM2\n" +
                    "J4X)LFH\n" +
                    "B1J)T6K\n" +
                    "4F6)PZT\n" +
                    "WN1)9WR\n" +
                    "VXM)3K7\n" +
                    "7RC)NW1\n" +
                    "TF2)9CM\n" +
                    "59Y)6WQ\n" +
                    "G7T)BF5\n" +
                    "Z4Q)JKJ\n" +
                    "ZCD)LT5\n" +
                    "2QP)MRX\n" +
                    "6TM)D79\n" +
                    "14T)KBG\n" +
                    "RHS)9KD\n" +
                    "7JS)Z4Q\n" +
                    "XVN)B1D\n" +
                    "Y7X)17K\n" +
                    "DRD)Q9Q\n" +
                    "3MH)BXK\n" +
                    "TCW)9TC\n" +
                    "9R4)NBY\n" +
                    "7ZG)B4M\n" +
                    "PPH)3LC\n" +
                    "9KD)VRQ\n" +
                    "91T)KSX\n" +
                    "FS2)3S9\n" +
                    "2WF)TWT\n" +
                    "PQJ)FQT\n" +
                    "8D8)ZGV\n" +
                    "1ZV)FN2\n" +
                    "4TB)LDQ\n" +
                    "JDY)6N8\n" +
                    "35N)756\n" +
                    "WPZ)V5R\n" +
                    "HYH)QK8\n" +
                    "JCS)JL9\n" +
                    "1Z8)MPR\n" +
                    "JPN)8W4\n" +
                    "34C)85G\n" +
                    "FNG)F35\n" +
                    "B3T)819\n" +
                    "PLQ)138\n" +
                    "VBJ)JTC\n" +
                    "JB3)FS1\n" +
                    "62X)LM8\n" +
                    "FZP)4SH\n" +
                    "1P7)LNM\n" +
                    "JZP)56P\n" +
                    "1QR)SQS\n" +
                    "VRQ)LMV\n" +
                    "WZG)7B1\n" +
                    "KPG)N3V\n" +
                    "4C6)VQS\n" +
                    "JQQ)MDR\n" +
                    "YCZ)69P\n" +
                    "RB8)9H5\n" +
                    "23R)9JW\n" +
                    "7XH)WRC\n" +
                    "JZ3)TYF\n" +
                    "5SG)1CH\n" +
                    "JNV)HCX\n" +
                    "312)QJG\n" +
                    "4T1)NS1\n" +
                    "64L)N1L\n" +
                    "6NK)LC1\n" +
                    "4WQ)FN6\n" +
                    "BKF)68D\n" +
                    "GB4)K95\n" +
                    "HX7)JPN\n" +
                    "W2M)6QS\n" +
                    "JSG)91T\n" +
                    "TP2)CWM\n" +
                    "NP1)S94\n" +
                    "3Y8)KWK\n" +
                    "2NM)ZJ5\n" +
                    "CBG)JC6\n" +
                    "KJB)ZPJ\n" +
                    "XPM)TF2\n" +
                    "BR7)L7C\n" +
                    "SHB)PY2\n" +
                    "PMG)F33\n" +
                    "2F1)Z36\n" +
                    "SS5)9K7\n" +
                    "73F)PL9\n" +
                    "6TH)9LP\n" +
                    "9MY)WHF\n" +
                    "63W)Q98\n" +
                    "YSP)DY7\n" +
                    "4WD)Z3C\n" +
                    "VCV)FNF\n" +
                    "QSW)PJZ\n" +
                    "PV4)9VL\n" +
                    "NY1)H37\n" +
                    "D81)NRC\n" +
                    "XYM)GP4\n" +
                    "JX4)LKF\n" +
                    "K81)FG6\n" +
                    "HMD)W34\n" +
                    "DYZ)8KY\n" +
                    "DY7)6WF\n" +
                    "8GC)ZDL\n" +
                    "WSS)X88\n" +
                    "DVV)R1B\n" +
                    "BB7)1DN\n" +
                    "3NC)7S4\n" +
                    "C12)TNS\n" +
                    "L2H)14T\n" +
                    "Y3P)92P\n" +
                    "W58)44W\n" +
                    "MCB)YPZ\n" +
                    "XQZ)DJH\n" +
                    "KQZ)MN2\n" +
                    "9WR)KCD\n" +
                    "2JM)D5L\n" +
                    "5Z7)9B7\n" +
                    "QKY)MV1\n" +
                    "K41)QKY\n" +
                    "VTF)BQ9\n" +
                    "NDZ)QNJ\n" +
                    "BGN)PJJ\n" +
                    "P77)6YV\n" +
                    "HT2)YWK\n" +
                    "PPJ)CQX\n" +
                    "H83)QSD\n" +
                    "VSV)Z8D\n" +
                    "LXN)QG8\n" +
                    "R87)3DM\n" +
                    "W6H)ZGN\n" +
                    "MKN)GD9\n" +
                    "3J7)1V9\n" +
                    "7FW)GQZ\n" +
                    "63H)WV5\n" +
                    "1PJ)5HM\n" +
                    "S88)SQ6\n" +
                    "XCH)PXL\n" +
                    "MSH)ZMH\n" +
                    "RR1)XJ8\n" +
                    "NTH)67R\n" +
                    "BWD)F1S\n" +
                    "JF8)9G7\n" +
                    "DYL)TNX\n" +
                    "W34)NVK\n" +
                    "8K3)53B\n" +
                    "75S)DVW\n" +
                    "4QX)3DS\n" +
                    "RSW)HQ1\n" +
                    "3HS)F2Q\n" +
                    "B4H)DX6\n" +
                    "6JX)HQL\n" +
                    "SV5)ZFX\n" +
                    "KJ1)WJ6\n" +
                    "89R)84D\n" +
                    "FJB)QYY\n" +
                    "K5S)55J\n" +
                    "F3G)WY8\n" +
                    "1CP)JTF\n" +
                    "WT9)LF9\n" +
                    "9TC)N8L\n" +
                    "FBP)R5D\n" +
                    "57B)D61\n" +
                    "XSG)3WX\n" +
                    "675)WHT\n" +
                    "B33)VYR\n" +
                    "K2H)3PN\n" +
                    "8ZB)SLB\n" +
                    "C1F)LLG\n" +
                    "3PN)5FH\n" +
                    "QKP)HL9\n" +
                    "G9S)3QY\n" +
                    "ZQF)F4T\n" +
                    "FXM)517\n" +
                    "L74)2HK\n" +
                    "V31)QJ3\n" +
                    "DDG)PY6\n" +
                    "3YW)6XG\n" +
                    "CXD)TBD\n" +
                    "K8W)J6H\n" +
                    "BX1)VS9\n" +
                    "LVJ)331\n" +
                    "B3J)4TY\n" +
                    "3S9)FRD\n" +
                    "CZ9)QD7\n" +
                    "718)SMJ\n" +
                    "53G)S8B\n" +
                    "LR3)W2M\n" +
                    "FRG)32P\n" +
                    "VBB)23R\n" +
                    "JM7)JY4\n" +
                    "3GM)HLB\n" +
                    "8HG)BCY\n" +
                    "CLV)WKS\n" +
                    "CFB)MW3\n" +
                    "8KY)FQM\n" +
                    "3N4)SD9\n" +
                    "C3T)DZZ\n" +
                    "75P)Z8Q\n" +
                    "MP2)VTS\n" +
                    "CW7)PZD\n" +
                    "GSV)TJJ\n" +
                    "5G8)WPZ\n" +
                    "45D)RGW\n" +
                    "VXC)2YG\n" +
                    "GLD)Y35\n" +
                    "L7C)P18\n" +
                    "PSB)PFS\n" +
                    "QPM)6R2\n" +
                    "1NB)BKF\n" +
                    "787)754\n" +
                    "KRC)B4D\n" +
                    "N5Q)DGP\n" +
                    "718)B5P\n" +
                    "44C)ST4\n" +
                    "XVY)45K\n" +
                    "WPB)VSB\n" +
                    "PKL)1WV\n" +
                    "7DG)37F\n" +
                    "QF5)QRB\n" +
                    "QC2)MK7\n" +
                    "KPZ)3SC\n" +
                    "8M2)LXX\n" +
                    "VPZ)45M\n" +
                    "V5M)34C\n" +
                    "JMQ)ZB6\n" +
                    "B4M)G18\n" +
                    "D6Y)DYT\n" +
                    "LFD)B9S\n" +
                    "R84)72H\n" +
                    "XP4)L74\n" +
                    "H37)BDG\n" +
                    "ZTS)NBK\n" +
                    "QKC)G3K\n" +
                    "7W1)FV4\n" +
                    "16P)M37\n" +
                    "ZSC)XJL\n" +
                    "B1D)VBJ\n" +
                    "RW8)5X5\n" +
                    "4D2)54L\n" +
                    "212)WZG\n" +
                    "NY3)TB2\n" +
                    "LR3)6D4\n" +
                    "KYJ)Z52\n" +
                    "9CM)98M\n" +
                    "RDB)LHB\n" +
                    "W48)V9J\n" +
                    "69X)ZFL\n" +
                    "45M)NV5\n" +
                    "54Q)QK1\n" +
                    "P18)B38\n" +
                    "QPD)1WG\n" +
                    "4DX)9HZ\n" +
                    "JC6)598\n" +
                    "LHT)8XB\n" +
                    "WKY)VMF\n" +
                    "RDV)PMX\n" +
                    "XLJ)LRG\n" +
                    "MPR)N15\n" +
                    "C9Z)FKC\n" +
                    "LZ5)C2K\n" +
                    "MW5)TFF\n" +
                    "FV4)9BW\n" +
                    "2RJ)K8W\n" +
                    "9GR)18Y\n" +
                    "1LD)JGG\n" +
                    "82Z)HKD\n" +
                    "7JS)4HT\n" +
                    "7NC)CXB\n" +
                    "2VZ)YL1\n" +
                    "PQR)JWN\n" +
                    "HZP)SV5\n" +
                    "212)42H\n" +
                    "QGD)J6P\n" +
                    "D5L)6NK\n" +
                    "XP7)6TM\n" +
                    "18Y)D48\n" +
                    "4TX)4NG\n" +
                    "NZJ)ZSC\n" +
                    "WGD)QWY\n" +
                    "NX4)66X\n" +
                    "2MG)BCF\n" +
                    "PSV)FVJ\n" +
                    "GD7)QC2\n" +
                    "DLZ)542\n" +
                    "2W1)DRN\n" +
                    "1WB)P6H\n" +
                    "KTF)H5W\n" +
                    "Y8J)9ZH\n" +
                    "JWB)PYW\n" +
                    "1DN)ZG6\n" +
                    "4MX)TSC\n" +
                    "5BF)PYB\n" +
                    "SLL)KSW\n" +
                    "RGR)4CS\n" +
                    "9T1)T26\n" +
                    "7H9)3SR\n" +
                    "BRP)TD9\n" +
                    "B73)C5P\n" +
                    "BXK)VN8\n" +
                    "4KT)6X5\n" +
                    "B65)BTV\n" +
                    "N88)2V5\n" +
                    "P2F)6SB\n" +
                    "PYW)QTV\n" +
                    "MJY)684\n" +
                    "JSF)P77\n" +
                    "LP4)P4J\n" +
                    "LKF)RNH\n" +
                    "SSB)3VB\n" +
                    "D75)F2D\n" +
                    "SD9)HDZ\n" +
                    "S46)1L7\n" +
                    "QYY)638\n" +
                    "XJJ)HJT\n" +
                    "R5D)Y72\n" +
                    "TXH)VN5\n" +
                    "WLD)HT2\n" +
                    "DLC)36P\n" +
                    "WS3)XLF\n" +
                    "HKD)V9F\n" +
                    "CKB)2YZ\n" +
                    "57X)RX9\n" +
                    "YKM)DTB\n" +
                    "4PR)G27\n" +
                    "T5W)55F\n" +
                    "PZD)JGT\n" +
                    "4CT)8FR\n" +
                    "HL9)W5B\n" +
                    "HWD)MW5\n" +
                    "XT6)2ZH\n" +
                    "BQH)9C8\n" +
                    "MY9)HV8\n" +
                    "X5S)RDN\n" +
                    "VSB)16C\n" +
                    "X86)3HW\n" +
                    "84D)26M\n" +
                    "MS5)M1C\n" +
                    "6X5)NWF\n" +
                    "9XS)L8X\n" +
                    "8R5)DXZ\n" +
                    "3KX)6B7\n" +
                    "S99)VWV\n" +
                    "5PV)D89\n" +
                    "FTS)8GR\n" +
                    "STY)9QL\n" +
                    "Z4L)6KM\n" +
                    "ZN3)Z27\n" +
                    "9G5)9F4\n" +
                    "7YP)167\n" +
                    "KF2)PX2\n" +
                    "72L)M4Y\n" +
                    "BSL)424\n" +
                    "Q7C)M4Q\n" +
                    "9GP)FJB\n" +
                    "SG6)NP1\n" +
                    "SVQ)QKC\n" +
                    "J3D)X5P\n" +
                    "KFR)RR8\n" +
                    "216)HMD\n" +
                    "KXN)93W\n" +
                    "Y8V)QGD\n" +
                    "Y8V)PV4\n" +
                    "248)LVD\n" +
                    "WFP)G1T\n" +
                    "NKZ)SNJ\n" +
                    "CX5)PSV\n" +
                    "QWD)THG\n" +
                    "J6P)C1T\n" +
                    "HV8)PMQ\n" +
                    "SGJ)MD4\n" +
                    "K3D)4Q2\n" +
                    "6R2)Z32\n" +
                    "KH9)72L\n" +
                    "9QQ)JR3\n" +
                    "B9P)4T7\n" +
                    "RNH)154\n" +
                    "6HQ)BRP\n" +
                    "HP9)WPB\n" +
                    "HGG)7DG\n" +
                    "27F)VSJ\n" +
                    "LW1)NWL\n" +
                    "GD7)LW1\n" +
                    "LWN)6TH\n" +
                    "9L1)TLR\n" +
                    "V7Q)3G5\n" +
                    "5P9)J3D\n" +
                    "B3N)XQT\n" +
                    "S59)5QP\n" +
                    "JR3)BW2\n" +
                    "2KM)R2V\n" +
                    "6KM)FNG\n" +
                    "6Q8)H2B\n" +
                    "CHD)RRQ\n" +
                    "4S5)7FY\n" +
                    "289)MWB\n" +
                    "73H)Y3P\n" +
                    "HYW)TXH\n" +
                    "X6L)XZX\n" +
                    "6YV)2YJ\n" +
                    "ZFL)4T6\n" +
                    "MM1)JX4\n" +
                    "63K)6D5\n" +
                    "P8G)Z9J\n" +
                    "NBY)Z4L\n" +
                    "DCT)LPH\n" +
                    "STQ)ZPT\n" +
                    "MCZ)VPZ\n" +
                    "KSX)YNK\n" +
                    "T6K)26J\n" +
                    "WWV)216\n" +
                    "LJW)Y3S\n" +
                    "W7D)VWC\n" +
                    "4SH)8MM\n" +
                    "NBY)6TD\n" +
                    "5HM)KQ9\n" +
                    "XP9)MQX\n" +
                    "YSL)3Y4\n" +
                    "NL2)DYL\n" +
                    "19L)8K3\n" +
                    "RZ1)9VC\n" +
                    "QVX)WVR\n" +
                    "9F4)Q3F\n" +
                    "2K5)N4X\n" +
                    "RF3)NHN\n" +
                    "WRC)G1G\n" +
                    "P8R)7TL\n" +
                    "XJ8)K6F\n" +
                    "5CZ)281\n" +
                    "B2Q)DG5\n" +
                    "5YC)XK3\n" +
                    "92K)DWK\n" +
                    "9ZH)YTR\n" +
                    "VWC)FQP\n" +
                    "BFM)B65\n" +
                    "Z9F)PDP\n" +
                    "8FR)6G7\n" +
                    "RDN)CHD\n" +
                    "XP3)RGR\n" +
                    "WVR)MMB\n" +
                    "7LB)5MB\n" +
                    "789)XCW\n" +
                    "V3L)19X\n" +
                    "689)2NM\n" +
                    "7DR)GLL\n" +
                    "RDV)Z4K\n" +
                    "HBH)F2Y\n" +
                    "HW4)B4W\n" +
                    "Z81)P8G\n" +
                    "XZ1)VYN\n" +
                    "T26)KDJ\n" +
                    "RCM)P2F\n" +
                    "F1Y)TCT\n" +
                    "T8D)V2B\n" +
                    "HV1)QPD\n" +
                    "KL3)CRS\n" +
                    "WY8)R42\n" +
                    "9VX)675\n" +
                    "6KN)LQQ\n" +
                    "LHF)NY1\n" +
                    "98Z)2VN\n" +
                    "3KG)JZP\n" +
                    "HHZ)2T6\n" +
                    "Q44)5JZ\n" +
                    "4HT)QF5\n" +
                    "9C2)FH4\n" +
                    "KFR)W9V\n" +
                    "L7G)4Y2\n" +
                    "GHC)L2H\n" +
                    "26J)YR4\n" +
                    "D9Z)XP4\n" +
                    "CRS)8MG\n" +
                    "J9B)P91\n" +
                    "J1C)8KQ\n" +
                    "CCR)M6M\n" +
                    "B52)PQC\n" +
                    "HLN)RSY\n" +
                    "QHM)G64\n" +
                    "BWR)47B\n" +
                    "G1G)8GC\n" +
                    "X6L)3TF\n" +
                    "FSG)7NN\n" +
                    "LF8)7FW\n" +
                    "WMD)WQQ\n" +
                    "45K)2MG\n" +
                    "MMB)JJ4\n" +
                    "3DS)XVN\n" +
                    "M2L)2X4\n" +
                    "ZYF)4JR\n" +
                    "MV2)Y4C\n" +
                    "PDP)JGN\n" +
                    "GWG)M2W\n" +
                    "XQT)DC1\n" +
                    "6QS)C28\n" +
                    "KRT)DMY\n" +
                    "NS1)L5X\n" +
                    "FY4)SK4\n" +
                    "ZPJ)HWH\n" +
                    "R39)PPQ\n" +
                    "J67)KNT\n" +
                    "DZ6)W48\n" +
                    "626)DGK\n" +
                    "4T7)VLZ\n" +
                    "HTJ)GLD\n" +
                    "PXL)PRZ\n" +
                    "DCW)WHP\n" +
                    "TDG)RDV\n" +
                    "GF6)F7V\n" +
                    "49C)DZ6\n" +
                    "3YR)5PR\n" +
                    "M8N)64L\n" +
                    "WHK)62X\n" +
                    "1WV)788\n" +
                    "ZPT)4MX\n" +
                    "NV5)58L\n" +
                    "9WY)8K9\n" +
                    "ZT9)D6Y\n" +
                    "MKN)S43\n" +
                    "Q65)Z73\n" +
                    "QPL)XVY\n" +
                    "X7B)NDQ\n" +
                    "153)BDX\n" +
                    "R2V)395\n" +
                    "YWK)N34\n" +
                    "ZMX)GX4\n" +
                    "3DJ)X11\n" +
                    "RHM)2VZ\n" +
                    "P3N)366\n" +
                    "ZRZ)6JX\n" +
                    "559)662\n" +
                    "WZ4)C8M\n" +
                    "KC4)VQC\n" +
                    "FS1)B3J\n" +
                    "72H)YWP\n" +
                    "H8L)TP2\n" +
                    "QK9)XXQ\n" +
                    "PL6)6PM\n" +
                    "32W)P8R\n" +
                    "YSV)4TX\n" +
                    "PY2)VD5\n" +
                    "LHB)4PR\n" +
                    "R1B)J4L\n" +
                    "36B)9NC\n" +
                    "FXF)4K5\n" +
                    "QPK)C3T\n" +
                    "VYN)VSW\n" +
                    "4NG)J65\n" +
                    "BZ8)LWN\n" +
                    "P5G)HJW\n" +
                    "2Z7)BX4\n" +
                    "BSK)16V\n" +
                    "S7S)9YQ\n" +
                    "TNS)5SG\n" +
                    "B3C)QK9\n" +
                    "KQ9)9L1\n" +
                    "VLZ)7Q7\n" +
                    "4PP)F1W\n" +
                    "2NG)F8R\n" +
                    "JH3)63W\n" +
                    "87R)KMF\n" +
                    "YPW)YGC\n" +
                    "F1L)BBD\n" +
                    "QLG)NH3\n" +
                    "S1H)K7Z\n" +
                    "F2D)DN4\n" +
                    "WJ9)BMS\n" +
                    "P7C)5YC\n" +
                    "428)HBF\n" +
                    "2HK)75P\n" +
                    "7S4)RT8\n" +
                    "D48)PL4\n" +
                    "B73)B5R\n" +
                    "9L7)1JK\n" +
                    "3G5)P7C\n" +
                    "B8P)BB7\n" +
                    "6G7)K2H\n" +
                    "598)V3L\n" +
                    "QBZ)BR7\n" +
                    "GQ5)HYW\n" +
                    "RLH)DCD\n" +
                    "BD9)CMV\n" +
                    "N34)J18\n" +
                    "3V7)KFR\n" +
                    "6N8)4J3\n" +
                    "J6H)QHN\n" +
                    "JGG)F6G\n" +
                    "WJ6)X5S\n" +
                    "KSJ)D81\n" +
                    "662)VCV\n" +
                    "4XT)B1J\n" +
                    "JWB)SXX\n" +
                    "XN6)XLJ\n" +
                    "LFH)TFP\n" +
                    "RT8)Y5D\n" +
                    "QKY)LY5\n" +
                    "PYB)FD7\n" +
                    "F1F)WDL\n" +
                    "CWM)RL5\n" +
                    "RR8)C8B\n" +
                    "18B)PWN\n" +
                    "F35)3HS\n" +
                    "B9S)7D4\n" +
                    "5BD)X79\n" +
                    "TGJ)9HF\n" +
                    "NNJ)235\n" +
                    "DTH)NDS\n" +
                    "GLL)CPY\n" +
                    "138)RXP\n" +
                    "X9Q)LHF\n" +
                    "WNV)DF5\n" +
                    "19N)46N\n" +
                    "QKV)BYV\n" +
                    "7TH)JNR\n" +
                    "GL3)288\n" +
                    "66Q)YYR\n" +
                    "SK4)4VH\n" +
                    "QNJ)XQZ\n" +
                    "7CC)278\n" +
                    "BDG)T8D\n" +
                    "WBM)YMW\n" +
                    "NCW)RHM\n" +
                    "2V7)YGW\n" +
                    "PYB)XSG\n" +
                    "RX9)YMP\n" +
                    "BCY)J1N\n" +
                    "JZ8)5CZ\n" +
                    "362)QVX\n" +
                    "517)QPM\n" +
                    "K74)3WF\n" +
                    "G9V)MHQ\n" +
                    "Z8Q)CJ2\n" +
                    "69M)54X\n" +
                    "STB)CHC\n" +
                    "VSW)GWD\n" +
                    "CMV)XTB\n" +
                    "17H)XNF\n" +
                    "CXG)HNZ\n" +
                    "HNR)LVJ\n" +
                    "S5B)QJR\n" +
                    "Z73)6MM\n" +
                    "WQT)7QR\n" +
                    "P6H)VHY\n" +
                    "BZ4)B33\n" +
                    "NM6)DKD\n" +
                    "9KV)419\n" +
                    "235)G2V\n" +
                    "K71)6MW\n" +
                    "T8Q)Y62\n" +
                    "68B)Q3S\n" +
                    "8MG)68B\n" +
                    "FSQ)3GM\n" +
                    "4XF)WJD\n" +
                    "FG6)36B\n" +
                    "DYZ)XDF\n" +
                    "BX4)XV7\n" +
                    "77F)WQR\n" +
                    "JTC)HTJ\n" +
                    "YZC)MVQ\n" +
                    "LM8)2B6\n" +
                    "ZB6)SXP\n" +
                    "PXC)5TP\n" +
                    "F6G)5FM\n" +
                    "G18)4WQ\n" +
                    "R4M)HFX\n" +
                    "HMP)2QP\n" +
                    "Q1L)2RJ\n" +
                    "QRB)9G5\n" +
                    "YJZ)STB\n" +
                    "3FH)3K3\n" +
                    "356)DKJ\n" +
                    "5GR)27Y\n" +
                    "BNQ)NC3\n" +
                    "36P)G7T\n" +
                    "YN2)HYX\n" +
                    "P76)39D\n" +
                    "PJS)YQX\n" +
                    "C76)C1P\n" +
                    "27Y)65Z\n" +
                    "HVY)37H\n" +
                    "462)16P\n" +
                    "N8L)Q44\n" +
                    "FQM)BWD\n" +
                    "54L)DQH\n" +
                    "455)P1T\n" +
                    "5GF)6JL\n" +
                    "JWR)WFT\n" +
                    "FG7)H2M\n" +
                    "DBT)J9B\n" +
                    "Q72)6KN\n" +
                    "756)BNQ\n" +
                    "MQG)HNR\n" +
                    "HDV)VGH\n" +
                    "FKM)MXF\n" +
                    "6PM)V7Q\n" +
                    "HPC)QWD\n" +
                    "G5M)Z1T\n" +
                    "FRD)8ZS\n" +
                    "ZPH)7TK\n" +
                    "KV4)NLS\n" +
                    "7QR)7NF\n" +
                    "RL5)JH3\n" +
                    "CPS)1HR\n" +
                    "BDX)B8P\n" +
                    "ZB6)XVB\n" +
                    "CS6)YXP\n" +
                    "W6C)C42\n" +
                    "STY)ZXK\n" +
                    "WXD)2TR\n" +
                    "KNT)J76\n" +
                    "XQ8)GQG\n" +
                    "1HR)D75\n" +
                    "MLH)56K\n" +
                    "PFS)X2B\n" +
                    "FVB)W7K\n" +
                    "6YQ)82Z\n" +
                    "RK3)XFT\n" +
                    "NRM)SG6\n" +
                    "9QL)VTF\n" +
                    "9TC)61T\n" +
                    "6RM)5GG\n" +
                    "8MM)H3Z\n" +
                    "SGC)KZ3\n" +
                    "7Q1)Z71\n" +
                    "HGL)FXD\n" +
                    "B69)4XT\n" +
                    "N1L)YQ2\n" +
                    "QV6)YCH\n" +
                    "K3N)KNV\n" +
                    "68D)BSL\n" +
                    "Y4C)HPL\n" +
                    "VDZ)WXD\n" +
                    "C5B)6SR\n" +
                    "PMQ)NVZ\n" +
                    "M35)NSK\n" +
                    "B4W)QCQ\n" +
                    "6FC)1GM\n" +
                    "7TS)N9B\n" +
                    "FN6)BKJ\n" +
                    "9H5)QL9\n" +
                    "KDJ)DCV\n" +
                    "LPH)W1G\n" +
                    "BQ9)SD1\n" +
                    "4Q2)KSQ\n" +
                    "6WF)4YZ\n" +
                    "M1W)5GF\n" +
                    "HYT)WVG\n" +
                    "HDZ)VBQ\n" +
                    "DZ6)VSS\n" +
                    "YTR)428\n" +
                    "T72)R8V\n" +
                    "F1S)C8R\n" +
                    "1FD)4ZK\n" +
                    "41J)626\n" +
                    "658)6CN\n" +
                    "HZ6)FNK\n" +
                    "FKM)1Z8\n" +
                    "6KV)NZJ\n" +
                    "F33)DJ1\n" +
                    "XTB)TSF\n" +
                    "NXV)RYS\n" +
                    "F1F)5MF\n" +
                    "YGW)2Z7\n" +
                    "MC2)CCR\n" +
                    "3YR)GSV\n" +
                    "XQK)XP7\n" +
                    "M97)PL6\n" +
                    "1CP)9ZP\n" +
                    "N8J)C9W\n" +
                    "GQZ)L6B\n" +
                    "HV1)SYH\n" +
                    "9VC)VZP\n" +
                    "QD7)5GC\n" +
                    "X2B)VT1\n" +
                    "92P)T5L\n" +
                    "XCW)WKY\n" +
                    "MY4)3J7\n" +
                    "MGN)3VL\n" +
                    "K7W)8R5\n" +
                    "HWH)BT3\n" +
                    "4PV)9R4\n" +
                    "FVJ)5BJ\n" +
                    "5MB)18B\n" +
                    "F8R)7RC\n" +
                    "MGN)N88\n" +
                    "1CH)ZPC\n" +
                    "X88)YN2\n" +
                    "Y8J)7C2\n" +
                    "1H5)R53\n" +
                    "BMJ)SV7\n" +
                    "LLG)G7X\n" +
                    "9LP)M97\n" +
                    "ZDL)B6H\n" +
                    "5WZ)MV2\n" +
                    "RVG)442\n" +
                    "W3R)CCX\n" +
                    "73K)L33\n" +
                    "17K)HGG\n" +
                    "LC7)GNV\n" +
                    "Q27)Q1L\n" +
                    "2HC)V2Z\n" +
                    "HXX)KC4\n" +
                    "6WQ)JCL\n" +
                    "T92)M8D\n" +
                    "KNV)6FC\n" +
                    "T9B)559\n" +
                    "RKY)DBT\n" +
                    "RRG)LRM\n" +
                    "DSQ)PCQ\n" +
                    "KF5)6YQ\n" +
                    "R8N)FXM\n" +
                    "JL9)KQK\n" +
                    "RCK)3P3\n" +
                    "8W4)XBP\n" +
                    "TNL)XYM\n" +
                    "4NG)Q26\n" +
                    "JX3)Q27\n" +
                    "GX4)8QH\n" +
                    "GTC)GD7\n" +
                    "LMV)XQK\n" +
                    "YZ8)2MX\n" +
                    "YL1)PFV\n" +
                    "VHW)WT9\n" +
                    "S99)58S\n" +
                    "13Q)NDZ\n" +
                    "LHB)LHT\n" +
                    "FQT)S59\n" +
                    "DX6)RWL\n" +
                    "288)MP2\n" +
                    "2LL)4H2\n" +
                    "ZPC)GTC\n" +
                    "HLN)4RR\n" +
                    "22J)9MY\n" +
                    "FH4)19L\n" +
                    "NF3)KRT\n" +
                    "JCL)DGR\n" +
                    "GSX)FSG\n" +
                    "TG1)X7B\n" +
                    "NHN)S46\n" +
                    "FZP)P5G\n" +
                    "S66)XTQ\n" +
                    "WQC)G1P\n" +
                    "XNT)QSX\n" +
                    "V14)673\n" +
                    "TLR)B9P\n" +
                    "2YP)ZPH\n" +
                    "FKC)VFR\n" +
                    "56K)QHM\n" +
                    "B9W)133\n" +
                    "TNV)P2L\n" +
                    "9NX)F98\n" +
                    "8KQ)5VP\n" +
                    "5PH)FY4\n" +
                    "6VK)S1H\n" +
                    "ZZM)M7R\n" +
                    "PLQ)MXZ\n" +
                    "GFY)RW8\n" +
                    "758)78F\n" +
                    "FQ1)JCY\n" +
                    "WV5)W58\n" +
                    "F3G)XPM\n" +
                    "GLX)GL5\n" +
                    "LQB)7BS\n" +
                    "Z55)GQ5\n" +
                    "THN)KH9\n" +
                    "5GG)V31\n" +
                    "G1P)FR3\n" +
                    "XFC)K5S\n" +
                    "HQ5)XBH\n" +
                    "HJT)FRG\n" +
                    "VSJ)MB3\n" +
                    "VHY)FQ1\n" +
                    "VL1)RDB\n" +
                    "L33)1NB\n" +
                    "M6M)LXJ\n" +
                    "BCF)J67\n" +
                    "6WT)B69\n" +
                    "FQT)R6B\n" +
                    "L3S)HS1\n" +
                    "VSS)C5B\n" +
                    "9FD)G5M\n" +
                    "P2L)GCB\n" +
                    "L5X)1VY\n" +
                    "26X)5Z7\n" +
                    "4D6)LWG\n" +
                    "8DZ)WT6\n" +
                    "XWG)V72\n" +
                    "QJ7)M1Z\n" +
                    "58S)HMN\n" +
                    "HJR)QY8\n" +
                    "L7S)ZYF\n" +
                    "MR5)5PV\n" +
                    "C8B)WFP\n" +
                    "QK8)1TX\n" +
                    "J12)2V7\n" +
                    "J76)RS8\n" +
                    "6MV)WJ3\n" +
                    "16C)HLY\n" +
                    "4TY)73H\n" +
                    "H6D)XQ8\n" +
                    "4JR)MX5\n" +
                    "M37)Q65\n" +
                    "W74)XX9\n" +
                    "TK5)49S\n" +
                    "B6H)BZ4\n" +
                    "F6N)BKV\n" +
                    "JF8)ZTS\n" +
                    "WBS)4LS\n" +
                    "LTH)J42\n" +
                    "JNL)6WT\n" +
                    "GL1)5Q3\n" +
                    "XJL)KVB\n" +
                    "YMW)MM1\n" +
                    "9HF)356\n" +
                    "5QP)7XH\n" +
                    "K95)KJ1\n" +
                    "QWY)8W6\n" +
                    "KPN)J1C\n" +
                    "RRQ)XNV\n" +
                    "419)XMQ\n" +
                    "YYR)9RZ\n" +
                    "1CT)KLZ\n" +
                    "8XQ)V5M\n" +
                    "XGT)ZN3\n" +
                    "WZ4)G8Z\n" +
                    "YWP)3MS\n" +
                    "93W)18V\n" +
                    "7FY)M8N\n" +
                    "TFP)NM4\n" +
                    "FR3)7N4\n" +
                    "JGN)NF3\n" +
                    "JDY)1P7\n" +
                    "M17)WS3\n" +
                    "SLQ)RVW\n" +
                    "DQJ)XR9\n" +
                    "FNF)89K\n" +
                    "YKH)KKH\n" +
                    "K6F)RPD\n" +
                    "J75)9GP\n" +
                    "2X9)DLD\n" +
                    "6CN)7W1\n" +
                    "7TK)MGN\n" +
                    "2SC)3KG\n" +
                    "BMS)MQG\n" +
                    "ZFX)53H\n" +
                    "Z3C)LT3\n" +
                    "VDN)GRY\n" +
                    "6JL)9Z9\n" +
                    "7NF)PML\n" +
                    "14T)WSX\n" +
                    "1V9)N7N\n" +
                    "N3V)HPD\n" +
                    "F53)PPJ\n" +
                    "DQ9)TNL\n" +
                    "JPH)1FL\n" +
                    "L1C)WBS\n" +
                    "RMY)BMJ\n" +
                    "MV1)1CP\n" +
                    "4GY)8M8\n" +
                    "CGN)4GC\n" +
                    "7B1)26V\n" +
                    "8QN)JSG\n" +
                    "VQC)XRT\n" +
                    "J1N)MKN\n" +
                    "PYS)289\n" +
                    "7Z9)HDV\n" +
                    "SJB)4C6\n" +
                    "LX3)HX7\n" +
                    "94G)R1P\n" +
                    "DY7)D6W\n" +
                    "3FH)2RV\n" +
                    "XKS)WHK\n" +
                    "FNB)6L2\n" +
                    "K6Y)NK7\n" +
                    "BYV)Z9F\n" +
                    "QBZ)FVB\n" +
                    "C5B)73F\n" +
                    "6SC)DMP\n" +
                    "B5R)K3N\n" +
                    "BKV)YKB\n" +
                    "VW8)1FD\n" +
                    "PWN)QPL\n" +
                    "DG5)BQH\n" +
                    "1MD)YCZ\n" +
                    "KWK)CZ9\n" +
                    "JY5)NX4\n" +
                    "F2T)8QR\n" +
                    "RYS)KF3\n" +
                    "LRM)M1W\n" +
                    "LXX)CD1\n" +
                    "98M)J4X\n" +
                    "D6Y)M17\n" +
                    "97S)BSK\n" +
                    "X11)2X9\n" +
                    "WKP)57B\n" +
                    "CCX)221\n" +
                    "GJM)T5M\n" +
                    "LT9)7YP\n" +
                    "RVW)FZP\n" +
                    "62K)CLV\n" +
                    "3VL)QQK\n" +
                    "3XD)HQ5\n" +
                    "W3R)QFC\n" +
                    "8JW)32H\n" +
                    "KCD)2HC\n" +
                    "SND)9FD\n" +
                    "4PR)D3D\n" +
                    "Q68)77F\n" +
                    "56P)87R\n" +
                    "SD1)RHS\n" +
                    "COM)2WF\n" +
                    "Q53)HBT\n" +
                    "ZJ5)68M\n" +
                    "4VH)VDN\n" +
                    "Z36)2QN\n" +
                    "FD6)R96\n" +
                    "NWP)HZP\n" +
                    "4T6)LGZ\n" +
                    "QTV)GF6\n" +
                    "S2P)HZ6\n" +
                    "XFC)S8R\n" +
                    "2V5)QDH\n" +
                    "PPQ)CD6\n" +
                    "Z71)YKH\n" +
                    "RYK)864\n" +
                    "VMF)MZQ\n" +
                    "KZK)KTF\n" +
                    "KZK)XKS\n" +
                    "SLK)WBM\n" +
                    "HWZ)CX5\n" +
                    "N1L)2HF\n" +
                    "54X)JWR\n" +
                    "TYF)YY5\n" +
                    "3DM)264\n" +
                    "FLG)FBP\n" +
                    "D2J)376\n" +
                    "2RV)JPH\n" +
                    "PMX)12Z\n" +
                    "CLB)7TS\n" +
                    "CNC)RCK\n" +
                    "281)8M2\n" +
                    "2SB)R4M\n" +
                    "KF3)1RN\n" +
                    "B38)4FG\n" +
                    "GV9)XV5\n" +
                    "33M)676\n" +
                    "QGN)HS2\n" +
                    "7D4)GFY\n" +
                    "4CT)STK\n" +
                    "N15)R1V\n" +
                    "29B)Q4W\n" +
                    "DXZ)BV8\n" +
                    "563)GLX\n" +
                    "XDF)GRS\n" +
                    "1LQ)TK5\n" +
                    "BPW)C93\n" +
                    "KP7)GLH\n" +
                    "2X2)F24\n" +
                    "YTR)LT9\n" +
                    "MN2)NNP\n" +
                    "W7K)TF6\n" +
                    "DGK)KPN\n" +
                    "D6W)PVB\n" +
                    "67R)3DJ\n" +
                    "TB6)NLV\n" +
                    "MDR)PLQ\n" +
                    "C92)3NQ\n" +
                    "F8D)1P3\n" +
                    "4ZK)T9B\n" +
                    "347)JJY\n" +
                    "XNF)6HQ\n" +
                    "QKK)63K\n" +
                    "B4H)HYH\n" +
                    "TCT)GFD\n" +
                    "CPW)5MK\n" +
                    "BQ8)789\n" +
                    "SGD)R84\n" +
                    "CBM)7XL\n" +
                    "NKX)4TB\n" +
                    "9K7)GTS\n" +
                    "VWL)3V7\n" +
                    "M1Z)7DX\n" +
                    "XXQ)W69\n" +
                    "676)Z55\n" +
                    "1NP)GW9\n" +
                    "HYX)Q7V\n" +
                    "YY5)5WZ\n" +
                    "7PK)Q12\n" +
                    "2VN)GWW\n" +
                    "NC3)SXB\n" +
                    "H5W)V14\n" +
                    "PQC)CPM\n" +
                    "JVM)RZL\n" +
                    "WQQ)R87\n" +
                    "YQ2)JCS\n" +
                    "3SR)MF9\n" +
                    "RPG)BZ8\n" +
                    "L36)CDK\n" +
                    "6WT)KSJ\n" +
                    "QSX)9RM\n" +
                    "STK)JM7\n" +
                    "DPL)CXG\n" +
                    "8DZ)FNV\n" +
                    "R96)7NC\n" +
                    "C5D)SAN\n" +
                    "1FM)4T1\n" +
                    "FXD)KCT\n" +
                    "K7W)347\n" +
                    "C1P)FS2\n" +
                    "C8R)Y4D\n" +
                    "F35)Q4Y\n" +
                    "3Y4)Q53\n" +
                    "WHF)212\n" +
                    "RMZ)TVV\n" +
                    "DKM)Y8V\n" +
                    "395)C76\n" +
                    "65Z)JF8\n" +
                    "4LS)CFB\n" +
                    "BJC)132\n" +
                    "P4J)WDH\n" +
                    "QQK)LCT\n" +
                    "TWS)LP4\n" +
                    "Q6W)XJJ\n" +
                    "GRS)JDY\n" +
                    "1WG)G46\n" +
                    "PCQ)X9P\n" +
                    "12Z)41J\n" +
                    "JF4)LXM\n" +
                    "F98)2LG\n" +
                    "DQH)15P\n" +
                    "DTB)9L7\n" +
                    "6XG)8D8\n" +
                    "TKW)2JM\n" +
                    "X5P)M35\n" +
                    "154)CGN\n" +
                    "7LW)KRQ\n" +
                    "KCT)57X\n" +
                    "9BW)QGN\n" +
                    "GHF)D2J\n" +
                    "Y72)HW4\n" +
                    "4V3)LFD\n" +
                    "ZXN)T3J\n" +
                    "W5B)L7G\n" +
                    "NP1)JGL\n" +
                    "6L2)J3G\n" +
                    "6B7)NTH\n" +
                    "DFT)DKM\n" +
                    "GP4)HXH\n" +
                    "FQP)THN\n" +
                    "XQ3)QPN\n" +
                    "H2M)ZCD\n" +
                    "37H)1RM\n" +
                    "MQM)BDT\n" +
                    "Y5Y)PZB\n" +
                    "WT6)B3N\n" +
                    "R7V)MSH\n" +
                    "2T8)T53\n" +
                    "3WX)WZ4\n" +
                    "WHP)69M\n" +
                    "YFS)NF8\n" +
                    "G3K)4TG\n" +
                    "V2B)3YR\n" +
                    "5HM)CLX\n" +
                    "5HK)75S\n" +
                    "HC5)SLQ\n" +
                    "55M)KPZ\n" +
                    "KKH)4CV\n" +
                    "B65)SJB\n" +
                    "TFF)1Y6\n" +
                    "5Q3)HJR\n" +
                    "MVQ)MCB\n" +
                    "12V)757\n" +
                    "YQX)V73\n" +
                    "9C8)JN8\n" +
                    "DYT)5PH\n" +
                    "C8M)69X\n" +
                    "VGH)S5T\n" +
                    "TNX)CXD\n" +
                    "XK3)TVX\n" +
                    "1L3)7RX\n" +
                    "662)B3T\n" +
                    "RTT)KQZ\n" +
                    "21H)RMF\n" +
                    "ZQF)2YP\n" +
                    "8ZS)7DR\n" +
                    "X8C)GY8\n" +
                    "HNZ)JPZ\n" +
                    "133)1NP\n" +
                    "PJJ)CPS\n" +
                    "18V)RPG\n" +
                    "9NC)STQ\n" +
                    "J1Y)3MH\n" +
                    "6SR)B73\n" +
                    "HPL)41V\n" +
                    "YMW)BPW\n" +
                    "RDJ)KN3\n" +
                    "LXM)P76\n" +
                    "42H)9W9\n" +
                    "CCD)W8T\n" +
                    "176)S7S\n" +
                    "B41)G6R\n" +
                    "KLZ)P19\n" +
                    "SQ6)XFC\n" +
                    "TF6)H89\n" +
                    "2FV)8DB\n" +
                    "4Y2)4D2\n" +
                    "JTF)TKW\n" +
                    "LDQ)X6L\n" +
                    "LT3)T3K\n" +
                    "QK1)GB4\n" +
                    "W4N)7Z9\n" +
                    "BKM)7CC\n" +
                    "65H)S2P\n" +
                    "8K9)YJZ\n" +
                    "253)9WY\n" +
                    "KVN)4PP\n" +
                    "2Z4)F3G\n" +
                    "C93)KTW\n" +
                    "5FM)QSW\n" +
                    "F24)4DX\n" +
                    "T3K)NR8\n" +
                    "3G7)RKY\n" +
                    "V73)6MV\n" +
                    "BT3)2F1\n" +
                    "HLY)CCD\n" +
                    "GLH)94G\n" +
                    "2CZ)W2J\n" +
                    "NSK)NC8\n" +
                    "V5H)M41\n" +
                    "19X)NXV\n" +
                    "QMQ)54Q\n" +
                    "LRG)Q48\n" +
                    "7CQ)YB2\n" +
                    "TSF)8XQ\n" +
                    "FCS)2VF\n" +
                    "16V)VXC\n" +
                    "HBZ)WGD\n" +
                    "VJV)JY5\n" +
                    "XRT)J2X\n" +
                    "424)5GR\n" +
                    "SXB)XJP\n" +
                    "BJC)5PJ\n" +
                    "SND)49C\n" +
                    "LC1)8Y7\n" +
                    "FR7)L6J\n" +
                    "H2M)XHR\n" +
                    "BW2)C9Z\n" +
                    "2HW)185\n" +
                    "TYL)2K5\n" +
                    "15P)6HZ\n" +
                    "LK7)YZ8\n" +
                    "JPZ)NNJ\n" +
                    "NGS)G3S\n" +
                    "GL5)QVR\n" +
                    "DJH)NZ6\n" +
                    "GKB)9S3\n" +
                    "JCX)Z42\n" +
                    "P2S)T92\n" +
                    "9ZN)ZCY\n" +
                    "PY6)DVV\n" +
                    "YP3)W5Z\n" +
                    "11M)WQT\n" +
                    "PQ9)G3Z\n" +
                    "2S1)SPV\n" +
                    "CQX)ZQF\n" +
                    "YPZ)LQ9\n" +
                    "VRQ)TZ9\n" +
                    "GY8)26X\n" +
                    "985)YQ3\n" +
                    "9ZP)9RP\n" +
                    "9JW)VL1\n" +
                    "4MX)33M\n" +
                    "L6J)L3S\n" +
                    "KBG)P3N\n" +
                    "G22)RPQ\n" +
                    "948)1FS\n" +
                    "3KS)CW7\n" +
                    "WCV)WNV\n" +
                    "LB9)KL3\n" +
                    "BDT)21H\n" +
                    "Q53)VB9\n" +
                    "HCV)2CZ\n" +
                    "7RX)TQM\n" +
                    "4GC)LDV\n" +
                    "PL9)N2M\n" +
                    "1VY)NL2\n" +
                    "R96)153\n" +
                    "37F)53G\n" +
                    "VT1)KF4\n" +
                    "61T)838\n" +
                    "HBT)R4N\n" +
                    "H81)TB6\n" +
                    "1FL)FR7\n" +
                    "J65)D9Z\n" +
                    "8Y7)22J\n" +
                    "KZ3)JFL\n" +
                    "W5B)B9W\n" +
                    "G27)QJ7\n" +
                    "V72)1MD\n" +
                    "5G8)J12\n" +
                    "T39)STH\n" +
                    "6JL)HCV\n" +
                    "SK4)K6Y\n" +
                    "Z1T)2FV\n" +
                    "PPJ)LJW\n" +
                    "JKJ)64J\n" +
                    "47Y)QGH\n" +
                    "N1V)CVT\n" +
                    "PJQ)TWQ\n" +
                    "26V)QMC\n" +
                    "5Y3)1QR\n" +
                    "F1W)VXM\n" +
                    "49S)QKP"
    );

    @Test
    public void testParse() {


        List<A2019_06.Edge> edges = A2019_06.parseInput(
                "COM)B\n" +
                        "B)C\n" +
                        "C)D\n" +
                        "D)E\n" +
                        "E)F\n" +
                        "B)G\n" +
                        "G)H\n" +
                        "D)I\n" +
                        "E)J\n" +
                        "J)K\n" +
                        "K)L"
        );


        assertEquals(11, edges.size());
    }

    @Test
    public void testHash() {

        List<A2019_06.Edge> edges = A2019_06.parseInput(
                "COM)B\n" +
                        "B)C\n" +
                        "C)D\n" +
                        "D)E\n" +
                        "E)F\n" +
                        "B)G\n" +
                        "G)H\n" +
                        "D)I\n" +
                        "E)J\n" +
                        "J)K\n" +
                        "K)L"
        );


        int hash = A2019_06.hash(edges);
        assertEquals(42, hash);
    }

    @Ignore("takes too long")
    @Test
    public void real() {

        List<A2019_06.Edge> edges = INPUT;


        int hash = A2019_06.hash(edges);
        assertEquals(322508, hash);
    }

    @Test
    public void testSantaSimple() {
        List<A2019_06.Edge> edges = A2019_06.parseInput(
                "COM)B\n" +
                        "B)C\n" +
                        "C)D\n" +
                        "D)E\n" +
                        "E)F\n" +
                        "B)G\n" +
                        "G)H\n" +
                        "D)I\n" +
                        "E)J\n" +
                        "J)K\n" +
                        "K)L\n" +
                        "K)YOU\n" +
                        "I)SAN"
        );


        int distance = A2019_06.PartTwo.distance(edges, "YOU", "SAN");

        assertEquals(6, distance);
    }

    @Test
    public void realPartTwo() {
        List<A2019_06.Edge> edges = INPUT;

        int distance = A2019_06.PartTwo.distance(edges, "YOU", "SAN");



        assertEquals(498, distance);
        int answer = distance-2;
        System.out.println("Answer: " + answer);
    }
}
